services:
  - type: web
    name: pfe-streamlit-assurance
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/app/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
